# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

to_newick_string <- function(tr, digits) {
    .Call('forest_to_newick_string', PACKAGE = 'forest', tr, digits)
}

from_newick_node <- function(x) {
    .Call('forest_from_newick_node', PACKAGE = 'forest', x)
}

from_newick_string <- function(tokens_str) {
    .Call('forest_from_newick_string', PACKAGE = 'forest', tokens_str)
}

from_ape_internal <- function(order, from, to, label, length) {
    .Call('forest_from_ape_internal', PACKAGE = 'forest', order, from, to, label, length)
}

to_ape_internal <- function(tr) {
    .Call('forest_to_ape_internal', PACKAGE = 'forest', tr)
}

drain_tree <- function(tr) {
    .Call('forest_drain_tree', PACKAGE = 'forest', tr)
}

classify <- function(tr, labels) {
    .Call('forest_classify', PACKAGE = 'forest', tr, labels)
}

plotting_coordinates <- function(tree) {
    .Call('forest_plotting_coordinates', PACKAGE = 'forest', tree)
}

plotting_coordinates_clade <- function(tree, n_taxa, p) {
    .Call('forest_plotting_coordinates_clade', PACKAGE = 'forest', tree, n_taxa, p)
}

forest_node__ctor <- function(label, length, data) {
    .Call('forest_forest_node__ctor', PACKAGE = 'forest', label, length, data)
}

forest_tree__root_subtree <- function(x) {
    .Call('forest_forest_tree__root_subtree', PACKAGE = 'forest', x)
}

forest_subtree__root_subtree <- function(x) {
    .Call('forest_forest_subtree__root_subtree', PACKAGE = 'forest', x)
}

forest_tree__set_root_subtree <- function(x, value) {
    invisible(.Call('forest_forest_tree__set_root_subtree', PACKAGE = 'forest', x, value))
}

forest_subtree__set_root_subtree <- function(x, value) {
    invisible(.Call('forest_forest_subtree__set_root_subtree', PACKAGE = 'forest', x, value))
}

forest_tree__root_node <- function(x) {
    .Call('forest_forest_tree__root_node', PACKAGE = 'forest', x)
}

forest_subtree__root_node <- function(x) {
    .Call('forest_forest_subtree__root_node', PACKAGE = 'forest', x)
}

forest_tree__set_root_node <- function(x, value) {
    invisible(.Call('forest_forest_tree__set_root_node', PACKAGE = 'forest', x, value))
}

forest_subtree__set_root_node <- function(x, value) {
    invisible(.Call('forest_forest_subtree__set_root_node', PACKAGE = 'forest', x, value))
}

forest_tree__child_subtree <- function(x, idx) {
    .Call('forest_forest_tree__child_subtree', PACKAGE = 'forest', x, idx)
}

forest_subtree__child_subtree <- function(x, idx) {
    .Call('forest_forest_subtree__child_subtree', PACKAGE = 'forest', x, idx)
}

forest_tree__set_child_subtree <- function(x, idx, value) {
    invisible(.Call('forest_forest_tree__set_child_subtree', PACKAGE = 'forest', x, idx, value))
}

forest_subtree__set_child_subtree <- function(x, idx, value) {
    invisible(.Call('forest_forest_subtree__set_child_subtree', PACKAGE = 'forest', x, idx, value))
}

forest_tree__child_node <- function(x, idx) {
    .Call('forest_forest_tree__child_node', PACKAGE = 'forest', x, idx)
}

forest_subtree__child_node <- function(x, idx) {
    .Call('forest_forest_subtree__child_node', PACKAGE = 'forest', x, idx)
}

forest_tree__set_child_node <- function(x, idx, value) {
    invisible(.Call('forest_forest_tree__set_child_node', PACKAGE = 'forest', x, idx, value))
}

forest_subtree__set_child_node <- function(x, idx, value) {
    invisible(.Call('forest_forest_subtree__set_child_node', PACKAGE = 'forest', x, idx, value))
}

forest_tree__subtree <- function(x, label) {
    .Call('forest_forest_tree__subtree', PACKAGE = 'forest', x, label)
}

forest_subtree__subtree <- function(x, label) {
    .Call('forest_forest_subtree__subtree', PACKAGE = 'forest', x, label)
}

forest_tree__ctor_empty <- function() {
    .Call('forest_forest_tree__ctor_empty', PACKAGE = 'forest')
}

forest_tree__ctor_node <- function(nd) {
    .Call('forest_forest_tree__ctor_node', PACKAGE = 'forest', nd)
}

forest_tree__empty <- function(tr) {
    .Call('forest_forest_tree__empty', PACKAGE = 'forest', tr)
}

forest_tree__size <- function(tr) {
    .Call('forest_forest_tree__size', PACKAGE = 'forest', tr)
}

forest_tree__arity <- function(tr) {
    .Call('forest_forest_tree__arity', PACKAGE = 'forest', tr)
}

forest_tree__childless <- function(tr) {
    .Call('forest_forest_tree__childless', PACKAGE = 'forest', tr)
}

forest_tree__representation <- function(tr) {
    .Call('forest_forest_tree__representation', PACKAGE = 'forest', tr)
}

forest_tree__clear <- function(x) {
    invisible(.Call('forest_forest_tree__clear', PACKAGE = 'forest', x))
}

forest_tree__count_tips <- function(tr) {
    .Call('forest_forest_tree__count_tips', PACKAGE = 'forest', tr)
}

forest_tree__count_nodes <- function(tr) {
    .Call('forest_forest_tree__count_nodes', PACKAGE = 'forest', tr)
}

forest_tree__tip_labels <- function(tr) {
    .Call('forest_forest_tree__tip_labels', PACKAGE = 'forest', tr)
}

forest_tree__node_labels <- function(tr) {
    .Call('forest_forest_tree__node_labels', PACKAGE = 'forest', tr)
}

forest_tree__heights <- function(tr) {
    .Call('forest_forest_tree__heights', PACKAGE = 'forest', tr)
}

forest_tree__depths <- function(tr) {
    .Call('forest_forest_tree__depths', PACKAGE = 'forest', tr)
}

forest_tree__is_binary <- function(tr) {
    .Call('forest_forest_tree__is_binary', PACKAGE = 'forest', tr)
}

forest_tree__has_branch_lengths <- function(tr) {
    .Call('forest_forest_tree__has_branch_lengths', PACKAGE = 'forest', tr)
}

forest_tree__is_ultrametric <- function(tr, eps) {
    .Call('forest_forest_tree__is_ultrametric', PACKAGE = 'forest', tr, eps)
}

forest_tree__update_heights <- function(x) {
    invisible(.Call('forest_forest_tree__update_heights', PACKAGE = 'forest', x))
}

forest_tree__collapse_singles <- function(x) {
    invisible(.Call('forest_forest_tree__collapse_singles', PACKAGE = 'forest', x))
}

forest_tree__ladderise <- function(x, right) {
    invisible(.Call('forest_forest_tree__ladderise', PACKAGE = 'forest', x, right))
}

forest_tree__drop_tips_by_label <- function(x, labels) {
    invisible(.Call('forest_forest_tree__drop_tips_by_label', PACKAGE = 'forest', x, labels))
}

forest_tree__rotate <- function(x, label) {
    invisible(.Call('forest_forest_tree__rotate', PACKAGE = 'forest', x, label))
}

forest_tree__check_names <- function(tr, labels, tip, node) {
    .Call('forest_forest_tree__check_names', PACKAGE = 'forest', tr, labels, tip, node)
}

forest_tree__associate_data <- function(x, data, tip, node) {
    invisible(.Call('forest_forest_tree__associate_data', PACKAGE = 'forest', x, data, tip, node))
}

forest_tree__copy_structure <- function(tr) {
    .Call('forest_forest_tree__copy_structure', PACKAGE = 'forest', tr)
}

forest_tree__copy <- function(tr) {
    .Call('forest_forest_tree__copy', PACKAGE = 'forest', tr)
}

forest_subtree__empty <- function(tr) {
    .Call('forest_forest_subtree__empty', PACKAGE = 'forest', tr)
}

forest_subtree__size <- function(tr) {
    .Call('forest_forest_subtree__size', PACKAGE = 'forest', tr)
}

forest_subtree__arity <- function(tr) {
    .Call('forest_forest_subtree__arity', PACKAGE = 'forest', tr)
}

forest_subtree__childless <- function(tr) {
    .Call('forest_forest_subtree__childless', PACKAGE = 'forest', tr)
}

forest_subtree__representation <- function(tr) {
    .Call('forest_forest_subtree__representation', PACKAGE = 'forest', tr)
}

forest_subtree__count_tips <- function(tr) {
    .Call('forest_forest_subtree__count_tips', PACKAGE = 'forest', tr)
}

forest_subtree__count_nodes <- function(tr) {
    .Call('forest_forest_subtree__count_nodes', PACKAGE = 'forest', tr)
}

forest_subtree__tip_labels <- function(tr) {
    .Call('forest_forest_subtree__tip_labels', PACKAGE = 'forest', tr)
}

forest_subtree__node_labels <- function(tr) {
    .Call('forest_forest_subtree__node_labels', PACKAGE = 'forest', tr)
}

forest_subtree__subtree_to_tree <- function(tr) {
    .Call('forest_forest_subtree__subtree_to_tree', PACKAGE = 'forest', tr)
}

