# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

to_newick_string <- function(tr, digits) {
    .Call('forest_to_newick_string', PACKAGE = 'forest', tr, digits)
}

from_newick_node <- function(x) {
    .Call('forest_from_newick_node', PACKAGE = 'forest', x)
}

from_newick_string <- function(tokens_str) {
    .Call('forest_from_newick_string', PACKAGE = 'forest', tokens_str)
}

from_ape_internal <- function(order, from, to, label, length) {
    .Call('forest_from_ape_internal', PACKAGE = 'forest', order, from, to, label, length)
}

to_ape_internal <- function(tr) {
    .Call('forest_to_ape_internal', PACKAGE = 'forest', tr)
}

drain_tree <- function(tr) {
    .Call('forest_drain_tree', PACKAGE = 'forest', tr)
}

classify <- function(tr, labels) {
    .Call('forest_classify', PACKAGE = 'forest', tr, labels)
}

plotting_coordinates <- function(tree) {
    .Call('forest_plotting_coordinates', PACKAGE = 'forest', tree)
}

plotting_coordinates_clade <- function(tree, n_taxa, p) {
    .Call('forest_plotting_coordinates_clade', PACKAGE = 'forest', tree, n_taxa, p)
}

